import {
  SlidersOutlined,
  SettingOutlined,
  MessageOutlined,
  PlusCircleOutlined,
  TeamOutlined,
  HomeOutlined,
  DatabaseOutlined,
  StockOutlined,
  DollarOutlined,
  BankOutlined,
  FundOutlined,
} from "@ant-design/icons";
import { APP_PREFIX_PATH, AUTH_PREFIX_PATH } from "configs/AppConfig";

const navTree = [
  {
    key: "extra",
    path: `${APP_PREFIX_PATH}/pages`,
    title: "sidenav.dashboard",
    icon: PlusCircleOutlined,
    breadcrumb: true,
    submenu: [
      {
        key: "home",
        path: `${APP_PREFIX_PATH}/home`,
        title: "home",
        icon: HomeOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "advance-requests",
        path: `${APP_PREFIX_PATH}`,
        title: "Advance Requests",
        icon: StockOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "normal-requests",
            path: `${APP_PREFIX_PATH}/normal-requests`,
            title: "Normal Requests",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "tsc-requests",
            path: `${APP_PREFIX_PATH}/tsc-requests`,
            title: "TSC Requests",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "top-ups",
            path: `${APP_PREFIX_PATH}/top-ups`,
            title: "Top Ups",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "stop-orders",
            path: `${APP_PREFIX_PATH}/stop-orders`,
            title: "Stop Orders",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "refunds",
            path: `${APP_PREFIX_PATH}/refunds`,
            title: "Refunds",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "datasheets",
        path: `${APP_PREFIX_PATH}`,
        title: "Datasheet",
        icon: DatabaseOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "datasheets-pending",
            path: `${APP_PREFIX_PATH}/datasheets-pending`,
            title: "Pending",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "datasheets-active",
            path: `${APP_PREFIX_PATH}/datasheets-active`,
            title: "Active",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "datasheets-processed",
            path: `${APP_PREFIX_PATH}/datasheets-processed`,
            title: "Processed",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "loan-requests",
        path: `${APP_PREFIX_PATH}`,
        title: "Loan Requests",
        icon: DollarOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "loan-requests-active-loans",
            path: `${APP_PREFIX_PATH}/loan-requests-active-loans`,
            title: "Active Loans",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "loan-requests-overdue-loans",
            path: `${APP_PREFIX_PATH}/loan-requests-overdue-loans`,
            title: "Overdue Loans",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "loan-requests-loan-defaulters",
            path: `${APP_PREFIX_PATH}/loan-requests-loan-defaulters`,
            title: "Loan Defaulters",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "loan-requests-repaid-loans",
            path: `${APP_PREFIX_PATH}/loan-requests-repaid-loans`,
            title: "Repaid Loans",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "disbursments",
        path: `${APP_PREFIX_PATH}`,
        title: "Disbursments",
        icon: FundOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "pending-disbursments",
            path: `${APP_PREFIX_PATH}/pending-disbursments`,
            title: "Pending Disbursments",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "processed-disbursments",
            path: `${APP_PREFIX_PATH}/processed-disbursments`,
            title: "Processed Disbursments",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "loan-reconciliations",
            path: `${APP_PREFIX_PATH}/loan-reconciliations`,
            title: "Loan Reconciliations",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "agencies",
        path: `${APP_PREFIX_PATH}`,
        title: "Agencies",
        icon: BankOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "agencies-agents",
            path: `${APP_PREFIX_PATH}/agencies-agents`,
            title: "Agents",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "agencies-invites",
            path: `${APP_PREFIX_PATH}/agencies-invites`,
            title: "Invites",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "agencies-refferal-commissions",
            path: `${APP_PREFIX_PATH}/agencies-refferal-commissions`,
            title: "Refferal Commission",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "messaging",
        path: `${APP_PREFIX_PATH}/apps/message/all-messages`,
        title: "Messaging",
        icon: MessageOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "user-management",
        path: `${APP_PREFIX_PATH}`,
        title: "User Management",
        icon: TeamOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "user-management-users",
            path: `${APP_PREFIX_PATH}/user-management-users`,
            title: "Users",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "user-management-approved",
            path: `${APP_PREFIX_PATH}/user-management-approved`,
            title: "Approved",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "user-management-roles-permissions",
            path: `${APP_PREFIX_PATH}/apps/roles-permissions/roles`,
            title: "Roles & Permissions",
            icon: "",
            breadcrumb: false,
            submenu: [],
          }
        ],
      },
      {
        key: "intitutions",
        path: `${APP_PREFIX_PATH}/institutions`,
        title: "Intitutions",
        icon: BankOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "reports",
        path: `${APP_PREFIX_PATH}`,
        title: "Reports",
        icon: SlidersOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "advance-requests",
            path: `${APP_PREFIX_PATH}/reports-advance-requests`,
            title: "Advance Requests",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "datasheets",
            path: `${APP_PREFIX_PATH}/reports-datasheets`,
            title: "Datasheets",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "Sales",
            path: `${APP_PREFIX_PATH}/reports-sales`,
            title: "Sales",
            icon: "",
            breadcrumb: true,
            submenu: [],
          }
        ],
      },
      {
        key: "Settings",
        path: `${APP_PREFIX_PATH}`,
        title: "settings",
        icon: SettingOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "company-settings",
            path: `${APP_PREFIX_PATH}/company-settings`,
            title: "Company Settings",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "default-settings",
            path: `${APP_PREFIX_PATH}/default-settings`,
            title: "default-settings",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "status",
            path: `${APP_PREFIX_PATH}/status`,
            title: "Status",
            icon: "",
            breadcrumb: true,
            submenu: [],
          }
        ],
      },
    ],
  },
];

const navigationConfig = [...navTree];

export default navigationConfig;
