export const MAINMENUDATA = "MAINMENUDATA";
export const SAVEMAINMENUDATA = "SAVEMAINMENUDATA";
export const NORMALREQUESTSMENU = "NORMALREQUESTSMENU";
export const TSCREQUESTSMENU = "TSCREQUESTSMENU";
export const SAVENORMALREQUESTSMENU = "SAVENORMALREQUESTSMENU";
export const SAVETSCREQUESTSMENU = "SAVETSCREQUESTSMENU";
export const GETREQUESTSDATA = "GETREQUESTSDATA";
export const SAVEREQUESTSDATA = "SAVEREQUESTSDATA";
export const GET_USER_REQUESTS_DATA = "GET_USER_REQUESTS_DATA";
export const SAVE_USER_REQUESTS_DATA = "SAVE_USER_REQUESTS_DATA";
export const POST_ADVANCE_REQUEST_ACTION = "POST_ADVANCE_REQUEST_ACTION";
export const GET_ADVANCE_REQUEST_ACTION_MESSAGE =
  "GET_ADVANCE_REQUEST_ACTION_MESSAGE";
export const CALCULATOR = "CALCULATOR";
export const CALCULATOR_RESPONSE_DATA = "CALCULATOR_RESPONSE_DATA";
