export const MAINMENUDATA = 'MAINMENUDATA';
export const SAVEMAINMENUDATA = 'SAVEMAINMENUDATA';
export const NORMALREQUESTSMENU = 'NORMALREQUESTSMENU';
export const TSCREQUESTSMENU = 'TSCREQUESTSMENU'
export const SAVENORMALREQUESTSMENU = 'SAVENORMALREQUESTSMENU';
export const SAVETSCREQUESTSMENU = 'SAVETSCREQUESTSMENU';;