export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const SAVE_INSTITUTIONS = "SAVE_INSTITUTIONS";
export const SAVE_INSTITUTE = "SAVE_INSTITUTE";
export const GET_INSTITUTE = "GET_INSTITUTE";
