export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const SAVE_INSTITUTIONS = "SAVE_INSTITUTIONS";
export const SAVE_INSTITUTE = "SAVE_INSTITUTE";
export const GET_INSTITUTE = "GET_INSTITUTE";
export const UPDATE_INSTITUTE = "UPDATE_INSTITUTE";
export const INSTITUTE_UPDATED = "INSTITUTE_UPDATED";
