export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const MESSAGE_SENT = "MESSAGE_SENT";
export const SAVE_MESSAGES = "SAVE_MESSAGES";

export const GET_TEMPLATE = "GET_TEMPLATE";
export const CREATE_TEMPLATE = "REATE_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";
export const GET_TEMPLATE_LIST = "GET_TEMPLATE_LIST";
export const SAVE_TEMPLATE = "SAVE_TEMPLATE";
export const SAVE_TEMPLATE_LIST = "SAVE_TEMPLATE_LIST";

export const GET_REMINDER = "GET_REMINDER";
export const GET_REMINDER_LIST = "GET_REMINDER_LIST";
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const CREATE_REMINDER = "CREATE_REMINDER";
export const SAVE_REMINDER = "SAVE_REMINDER";
export const SAVE_REMINDER_LIST = "SAVE_REMINDER_LIST";

export const MESSAGE_UPDATE = "MESSAGE_UPDATE";
