export const GET_ROLES = "GET_USER_ROLES";
export const GET_USER_ROLES = "GET_USER_ROLES";
export const SAVE_ROLES = "SAVE_ROLES";
export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const ROLE_DETAILS = "ROLE_DETAILS";
export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const SAVE_PERMISSIONS = "SAVE_PERMISSIONS";
