export const GET_USERS = "GET_USER";
export const SAVE_USERS = "SAVE_USERS";
export const SAVE_WEEKLY_DATA = "SAVE_WEEKLY_DATA";
export const GET_WEEKLY_DATA = "GET_WEEKLY_DATA"
export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const SAVE_USER = "SAVE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const USER_UPDATED = "USER_UPDATED"
export const CHANGE_USER_ROLE = "CHANGE_USER_ROLE"
export const CHANGE_USER_TYPE = "CHANGE_USER_TYPE"
export const DEACTIVATE_USER = "DEACTIVATE_USER"
export const ACTIVATE_USER = "ACTIVATE_USER"
export const DECLINE_USER = "DECLINE_USER"
export const APPROVE_USER = "APPROVE_USER"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"

